name: Pull in Live Server At Schduled Time

on: 
  workflow_dispatch:

jobs:
  Add_Cronjob:
    runs-on: ubuntu-latest
    steps:
      - name: Executing the Script to Add CronJob 
        env:
          cron: "15 17 * * *"
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh.pem
          chmod 600 ssh.pem
          ssh -o StrictHostKeyChecking=no -i ssh.pem ubuntu@64.227.162.80 "cd live_server_script && ./github_action.sh '$cron' 'bench-ps' 'pcpl'"